### ISSUE TITLE
Limit python version installation

### ISSUE THREAD

**Issue by antoniovazquezblanco** [MKuranowski/aiocsv#1]
Please add python version checks before installation.

See https://packaging.python.org/guides/distributing-packages-using-setuptools/#id55

Maybe it would be a good idea considering relaying on typing extensions:

https://github.com/python/typing/tree/master/typing_extensions

Thank you!

**Comment by MKuranowski** [comment]
Thanks for reporting.

I added support for 3.6 and 3.7 with typing-extensions; and also configured Travis CI to runs tests on 3.6, 3.7 and 3.8.

**Comment by antoniovazquezblanco** [comment]
Awesome!
