### ISSUE TITLE
No `line_num`?

### ISSUE THREAD

**Issue by YaraslauZhylko** [MKuranowski/aiocsv#19]
Hi!

Is there a reason why `line_num` functionality is not implemented for the `AsyncReader`?

Seems to be as easy as adding `self._line_num += 1` to the `AsyncReader.__anext__()` method.

Are there any less obvious implementation details that I'm missing? :thinking:

**Comment by MKuranowski** [comment]
This would track record numbers, not line numbers. Records can span multiple lines.

**Comment by YaraslauZhylko** [comment]
Makes sense.

Still, `csv` nadles the actual line count inside the `reader` class.
And in `aiocsv` its functionality is basically replaced by `parser`/`_parser` that seem to be aware of the nmbe rfo new lines that got processed to get one record.

Will it be hard to implment the count there?

**Comment by MKuranowski** [comment]
This should probably be easy to implement, since parser is internal it can just `yield line_num, record` instead of `yield record`. I just never been bothered to implement this.

**Comment by YaraslauZhylko** [comment]
In my particular case I need to report CSV file errors and I need the actual line numner to associate with the error.
