### ISSUE TITLE
mypy error on parser.py:220

### ISSUE THREAD

**Issue by hellocoldworld** [MKuranowski/aiocsv#25]
mypy1.0.1 reports Invalid "type: ignore" comment  [syntax] in the following line

https://github.com/MKuranowski/aiocsv/blob/d92c113d08ddfdfc34bbc760addc77d33a3cf4e9/aiocsv/parser.py#L220C1-L221C1

... maybe add the coloquial expression in a separate comment? Or investigate what is happenning further?

**Comment by MKuranowski** [comment]
If that's bothering you, feel free to open up a PR – [PEP 484](https://peps.python.org/pep-0484/#type-comments) says it should be `# type: ignore # wtf`, but this might not even be necessary now.
