### ISSUE TITLE
allow line number to be settable

### ISSUE THREAD

**Issue by drobert** [MKuranowski/aiocsv#31]
I am genuinely appreciative that this is clearly documented:

> AsyncReader.line_num, AsyncDictReader.line_num and AsyncDictReader.dialect are not settable,

However I have a valid use case for wanting to set this so I figured I'd open a ticket.

We have a relatively slow line-by-line streaming process from an s3 file through AsyncDictReader. Something upstream in the network occasionally severs the connection, leaving the file part-way read. We catch this exception and maintain some internal state, including upstream bytes read from s3 and the internal buffer of characters read from s3 but not yet consumed by the dict reader. We then re-request the s3 object with a Range header, allowing us to effectively resume the read.

Unfortunately, we can't set the state of the parser when we resume the process to include the line number from the original request; it would only know line numbers from the 'part' of the file requested in subsequent attempts.

If the line number is purely an internal thing and is never surfaced in any exception message, then I suppose this is a moot point and can be closed, though it does obviate the usefulness of AsyncReader.line_num

(Update: actually, to do this effectively I'd also want a mechanism to retrive the internal Parser's buffer. This works in the python version but not the C version.)

**Comment by MKuranowski** [comment]
That feature is not available in the built-in csv issue:

```py
>>> import csv
>>> r = csv.reader(["pi,3.14", "e,2.71", "sqrt2,1.41"])
>>> r.line_num = 100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: readonly attribute
```

Given that the behavior in aiocsv is the same as in builtin csv, I'm closing the issue; but I don't really see a reason why it couldn't be settable, it might be worth to file an issue in CPython.
