### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by hellocoldworld** [MKuranowski/aiocsv#8]
Hello, would you be open into adding types to aiocsv? I could help

**Comment by MKuranowski** [comment]
`aiocsv` already uses type hints everywhere

**Comment by hellocoldworld** [comment]
Hi @MKuranowski ! Great! I didn't know this, because Mypy reports that there are no type hints available. I think the standard way to mark the package as a typed one is adding a `py.typed` marker file as per PEP561

**Comment by MKuranowski** [comment]
Added, pushed in release 1.2.2

**Comment by hellocoldworld** [comment]
Thanks! @MKuranowski  upgraded and it's looking fine!
