### ISSUE TITLE
Installing on ARM-based machines

### ISSUE THREAD

**Issue by pudo** [MKuranowski/aiocsv#9]
Thanks for the wonderful package! I'm seeing some issues with 1.2.2 on ARM-based machines - both in GitHub Actions buildx and on my local Mac (Py 3.10.2, M1 machine). You can see the issue here: https://github.com/opensanctions/yente/runs/6052901093?check_suite_focus=true - I'm curious if by any chance you disabled the upload of universal/source wheels some time recently? Is there actually C code in this package?

**Comment by MKuranowski** [comment]
The CSV parser is written using Cython, so yes, there's a C extension in use. However I think the source-distribution package is missing on PyPi; MacOS and Linux should have no trouble building the extension on their own.

**Comment by MKuranowski** [comment]
Source package uploaded; I can now build aiocsv on ARM Linux.

**Comment by pudo** [comment]
Wow, appreciate the sunday fix very much! Thanks!
